"""Shared primitives for the e1f ETF tooling.

Command modules keep importing from ``e1f.common`` (ADR-0003). The package
split (ADR-0025) is an internal layout: one module per concern, re-exported
here so existing import paths stay valid.
"""

from .currency_metadata import CurrencyMetadata, CurrencyMetadataError
from .defaults import (
    BASE_CURRENCY,
    DEFAULT_CONFIG,
    DEFAULT_CURRENCY_META,
    DEFAULT_DB,
    DEFAULT_GLOSSARY,
    DEFAULT_SCENARIOS,
    DEFAULT_START_DATE,
    UNSUPPORTED_FX_CURRENCIES,
    XTB_EXCHANGE_SUFFIX,
)
from .holdings import (
    HoldingSeries,
    PositionEvent,
    build_series,
    close_asof,
    convert_to_eur,
    fund_eur_value,
    fx_rate_asof,
    load_price_series,
    load_trades,
    pinned_quote_currency,
    portfolio_isins,
    position_asof,
    position_timeline,
    price_date_asof,
    unit_value_on,
    value_on,
)
from .metrics import (
    MetricContract,
    Status,
    _explain_metric,
    _limited_by,
    xirr,
)
from .rebalance import (
    RebalancePlan,
    _FLOAT_CLAMP,
    assemble_rebalance_valuations,
    compute_rebalance,
    post_rebalance_weights,
)
from .returns import (
    aggregate_value_series,
    contribution_on,
    contribution_to_return,
    eur_return_series,
    portfolio_return_series,
    wealth_and_returns,
)
from .retry import call_with_retry
from .scenarios import (
    Scenario,
    ScenarioError,
    delete_scenario,
    get_scenario,
    load_scenarios,
    save_scenario,
)
from .universe import (
    ConfigManager,
    ETFDefinition,
    OpenFIGIResolver,
    distribution_from_name,
    enrich_fund_metadata,
    fund_currency_from_name,
)

__all__ = [
    "BASE_CURRENCY",
    "DEFAULT_CONFIG",
    "DEFAULT_CURRENCY_META",
    "DEFAULT_DB",
    "DEFAULT_GLOSSARY",
    "DEFAULT_SCENARIOS",
    "DEFAULT_START_DATE",
    "UNSUPPORTED_FX_CURRENCIES",
    "XTB_EXCHANGE_SUFFIX",
    "_FLOAT_CLAMP",
    "ConfigManager",
    "CurrencyMetadata",
    "CurrencyMetadataError",
    "ETFDefinition",
    "HoldingSeries",
    "MetricContract",
    "OpenFIGIResolver",
    "PositionEvent",
    "RebalancePlan",
    "Scenario",
    "ScenarioError",
    "Status",
    "_explain_metric",
    "_limited_by",
    "aggregate_value_series",
    "assemble_rebalance_valuations",
    "build_series",
    "call_with_retry",
    "close_asof",
    "compute_rebalance",
    "contribution_on",
    "contribution_to_return",
    "convert_to_eur",
    "delete_scenario",
    "distribution_from_name",
    "enrich_fund_metadata",
    "eur_return_series",
    "fund_currency_from_name",
    "fund_eur_value",
    "fx_rate_asof",
    "get_scenario",
    "load_price_series",
    "load_scenarios",
    "load_trades",
    "pinned_quote_currency",
    "portfolio_isins",
    "portfolio_return_series",
    "position_asof",
    "position_timeline",
    "post_rebalance_weights",
    "price_date_asof",
    "save_scenario",
    "unit_value_on",
    "value_on",
    "wealth_and_returns",
    "xirr",
]
